### ISSUE TITLE
Refactor for best practice using react

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1112]
In the Pre-Alpha and Alpha Abbey Wood versions, the overall usage of react was not totally aligned with current best practice in the community. This is also partially the reason why BlockSuite started the project without react (which turns out to be successful). So from Downhills, we are working on refactoring the react codebase, following the modern practice, removing anti-pattern code, making it maintainable in the long-term.

**Comment by doodlewind** [comment]
@Himself65 please link some notable related progress here, thanks!

**Comment by himself65** [comment]
## DataCenter

Data Center should allow running in SSR mode, which will also benefit the SEO and SSR in public-workspac

First we need to allow fetch data in server side.

```ts
fetch('/data/api') // this is prohibited in server side
// should change to
fetch('http://xxx/data/api')
```

See related PR
- https://github.com/toeverything/AFFiNE/pull/1106

Second is to improve the test coverage in affine provider. I'm figuring out setup a test environment for API

## GlobalState

Now we're using zustand to manage the global state like `currentWorkspace,` `currentPage,` `dataCenter`...

- https://github.com/toeverything/AFFiNE/issues/973
- https://github.com/toeverything/AFFiNE/pull/1001
- https://github.com/toeverything/AFFiNE/pull/998
- https://github.com/toeverything/AFFiNE/pull/1109

The next thing is to use suspense mode to replace `useStaet` + `useEffect` to load async data from OctoBase server. I'm thinking of using `useSWR` to replace the code. But for the best practice, we need to wait until `React@18.3.0` for `use` API.

### State Syncing

For example, when you click `add member,` the list should also have the same members. Sometimes state doesn't be synced because they're isolated and don't have connection with each other.

## Suspend + ErrorBoundary

Instead of `router.push('404')` `return <Loading/>` we should use suspense mode and ErrorBoundary to handle them.

See: https://swr.vercel.app/docs/suspense

## BlockSuite

BlockSuite page should have only one instance in whole AFFiNE lifecycle, which will boost up the switching page time speed.

## DX

- TypeScript improvement
- Strict ESLint rules
- Reduce unused packages
- Advanced debug log

**Comment by darkskygit** [comment]
> BlockSuite page should have only one instance in whole AFFiNE lifecycle, which will boost up the switching page time speed.

We may need a series of test cases to ensure that the memory data is fully recycled after switching pages.
