### ISSUE TITLE
Flickering animation on switching between Edgeless and Paper mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1149]
Animation flickers when performing mouse-in / mouse-out in a high frequency.

https://user-images.githubusercontent.com/7312949/220222206-59f4f268-f9f0-48ac-bc08-eb50da211561.MOV

/cc @xell @VelikaHF

**Comment by xell** [comment]
And it seems there's another edge case that if the cursor *stays* right in somewhere near the middle line, two switch modes will *crazily* turn into each other. Due to the frame rate limitation of the screencast, the craziness of the movements doesn't express explicitly. The actual speed is 20 times of it.


https://user-images.githubusercontent.com/132558/220237319-76b1f46b-7ab5-4868-a041-129ed51a07e1.mp4
