### ISSUE TITLE
feat: disable default "save page as" keyboard shortcut

### ISSUE THREAD

**Issue by yjl9903** [toeverything/AFFiNE#1541]
## Description

Currently, pressing `cmd+s` / `ctrl+s` when writing in the block editor will open the browser default "save page as" window to save the current HTML page to a local file.

People tired of old office software may frequently press this shortcut to avoid loss of work progress. And edition has been synced with yjs so that there is no concept of "saving" here?

## Solution

I think we can disable this shortcut to avoid interrupting the writing flow.

**Comment by doodlewind** [comment]
I think "save as" is the default browser action, and when using AFFiNE, we always save as you type, so no explicit saving is required. Not sure if disabling the default browser behavior makes sense here, since it may also be weird if nothing happen after pressing `cmd-S`.

/cc @joebeijing

**Comment by yjl9903** [comment]
Yes. Maybe we can display some notification after pressing `cmd-S`, i.e. fake message like "Things have been saved" or help message "There is no need to save manually".

And we can display the current sync status (sync timestamp and whether it is local only)? 

Just like notion, tencent docs or shimo, display messages below when pressing `cmd-S`

![image](https://user-images.githubusercontent.com/30072175/224525396-e3177c30-f18f-415b-89f2-ec76a6c87691.png)

![image](https://user-images.githubusercontent.com/30072175/224525264-840e7a28-50a5-4c78-868a-dc44b12a6974.png)

![image](https://user-images.githubusercontent.com/30072175/224525285-f8e7dcd9-c0f6-4370-bc1e-8a28baac6778.png)

For overleaf, texpage and other online latex editor, it does latex compilation when pressing  `cmd-S`.

**Comment by joebeijing** [comment]
Thank you for your feedback, agree with that. @yjl9903 
Actually, we received similar feedback for the pre-alpha version as well. Although we save changes in real time, users have been conditioned to expect a certain level of safety when it comes to their work. If we don’t do anything, it will keep triggering the operation to save the page.

Here are the solutions we are considering:

If it’s a local workspace, triggering ⌘/ctrl + S will display a Toast message that says: “All changes are saved locally in real time.”

If it’s a cloud workspace and the network is working fine, triggering ⌘/ctrl + S will manually start syncing. Although we haven’t implemented this yet, we plan to show the following Toast messages one after another:
• Syncing with AFFiNE Cloud (sync starts)
• Saved to AFFiNE Cloud (sync completes)

If it’s a cloud workspace but the network is offline, triggering it will display a Toast message that says: “All changes are saved locally since you are currently offline.”

**Comment by Ibtixam** [comment]
Is still open I can contribute. I can this feature.

**Comment by iprime2** [comment]
can someone tell how I can setup this and run locally?
@houjoe0829

**Comment by houjoe0829** [comment]
> can someone tell how I can setup this and run locally? @houjoe0829

Hi, the Docker version that can currently be deployed locally has not been updated yet.  https://github.com/toeverything/docker

**Comment by iprime2** [comment]
Please let me know when it will updated

**Comment by houjoe0829** [comment]
> Please let me know when it will updated

There is no specific time at the moment, as it is still being processed.

**Comment by iprime2** [comment]
Can I run this project on gitpod @houjoe0829

**Comment by houjoe0829** [comment]
@Brooooooklyn need your help to take a look at this, thank you.

**Comment by vikashsprem** [comment]
> Thank you for your feedback, agree with that. @yjl9903 Actually, we received similar feedback for the pre-alpha version as well. Although we save changes in real time, users have been conditioned to expect a certain level of safety when it comes to their work. If we don’t do anything, it will keep triggering the operation to save the page.
> 
> Here are the solutions we are considering:
> 
> If it’s a local workspace, triggering ⌘/ctrl + S will display a Toast message that says: “All changes are saved locally in real time.”
> 
> If it’s a cloud workspace and the network is working fine, triggering ⌘/ctrl + S will manually start syncing. Although we haven’t implemented this yet, we plan to show the following Toast messages one after another: • Syncing with AFFiNE Cloud (sync starts) • Saved to AFFiNE Cloud (sync completes)
> 
> If it’s a cloud workspace but the network is offline, triggering it will display a Toast message that says: “All changes are saved locally since you are currently offline.”

Should I go for it?
