### ISSUE TITLE
AFFiNE client supports spelling check

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2592]
- It is enabled by default and can be disabled.
- Users can set the language for spell check.

**Comment by reisaraujo-miguel** [comment]
Is this really fixed? I am using the flatpak version of the app, version 0.25.1, and although I can enable spell checking, I can't select the language. It just uses my system language, which is English, and I would like to set it to Portuguese (or multi-language if possible) because it is the language I usually write on.
