### ISSUE TITLE
In offline mode, can not load preloading content when creating a new workspace.

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#3003]
https://github.com/toeverything/AFFiNE/assets/22443345/be28d14b-2072-4b1b-8ff1-5d5a879fcc87

The main issue that needs to be fixed is that the pre-set content should ideally be a local static resource.

**Comment by Kaneki-Ken-7** [comment]
Hey @himself65 I found the problem is in this preloading file where the image prop is having a live URL instead of local static path for the image. Can you tell me like what should I write as path there . Then I can do it for every other image and gifs there and store it in web/public/imgs . Here is SS of the issue : 
![preloading json - AFFiNE - Visual Studio Code 06-07-2023 12_00_44 (2)](https://github.com/toeverything/AFFiNE/assets/30045569/8dfd1c69-203e-45e5-84ef-27e9f3b39bc0)

**Comment by himself65** [comment]
I'm working on this
