### ISSUE TITLE
Vim keybindings​

### ISSUE THREAD

**Issue by ryanwwest** [toeverything/AFFiNE#3236]
### Description

Tools like obsidian.md and silverbullet.md offer a Vim mode for advanced keyboard users, even in non-traditional word editor views such as in an Obsidian Canvas page. It would be nice to have Vim-mode in AFFiNE as well.

### Use case

Developers and others that have learned the Vim keybindings would be able to use the keyboard much more exclusively to save time and be more productive. Vim keybindings are somewhat 'universal' in the sense that many cross-platforms applications support them, so you immediately gain a decent-sized, tech-centric crowd by offering them.

### Anything else?

There is a CodeMirror 6 plugin that makes this easy (see https://github.com/silverbulletmd/silverbullet/issues/149), though that may not be relevant here.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Thank you very much for your feedback. This is an interesting point. However, it is currently not in the plan. We have taken note of it and hope to revisit it after handling higher priority features. If you have any questions, please feel free to reopen this issue at any time.

**Comment by ElnuDev** [comment]
Not offering Vim keybinds is a dealbreaker for me and anyone who is used to Vim keybinds, so that's sad to hear, especially considering many similar projects support a Vim mode. Even Logseq has one albeit through extensions.

**Comment by Microwave-WYB** [comment]
I would much prefer having even some basic support of Vim keybindings. I would rather edit my document in Vim then copy & paste into the app

**Comment by pascalwhoop** [comment]
@houjoe0829 if the community builds this, why not bring it in and hide it behind a feature flag? Many powerusers are vim users and so used to editing files with vim, we often use our IDEs as note tools > notion and others because of the familiarity. And since it's behind a feature flag, it would not affect any standard users but be a huge switching reason for everyone who falls into the
- pro user
- cares about privacy
- takes note not just on their laptop

bucket.

**Comment by CX330Blake** [comment]
+1

**Comment by JPhusion** [comment]
+1

**Comment by Eko450-eng** [comment]
+1

**Comment by Rigo-m** [comment]
I hate writing "+1"... But this should be at least an open discussion issue, being marked as not planned would mean "never ever in the history of affine"

**Comment by freeo** [comment]
Unfortunately, this is reason enough to fork.
Why split a community where vim users + contributors could give back to the main project? Not supporting vim means not living up to the potential of this app. This could be greater than emacs org-mode (with evil mode), if the decision is made to create _one big community_ instead of a fork which would fragment the AFFiNE community.
