### ISSUE TITLE
​0.7.0-canary.55，setting-workspace，there are more untitled workspaces

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#3427]
### What happened?

as the title, and i got a picture below:
![image](https://github.com/toeverything/AFFiNE/assets/30165217/c50ae6ff-205f-456b-aeb8-de43d3229943)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
I believe this should be fixed in canary.56.
If not, feel free to reopen the issue

**Comment by Mojicode** [comment]
> I believe this should be fixed in canary.56. If not, feel free to reopen the issue

canary.57, there are still more untitled workspaces.
![image](https://github.com/toeverything/AFFiNE/assets/30165217/6067d465-a139-49e1-9982-2da42ff92bfc)

**Comment by himself65** [comment]
@pengx17

**Comment by pengx17** [comment]
Sorry but I guess you need to cleanup these workspaces. The fastest way to delete all of these is to remove the cache folder, which will remove ALL data for the canary version. Before doing this, please export the workspace through setting before doing so.

- Open cmd (search for cmd in the Start menu).
- Copy the following and press Enter:
`rd /s /q "C:\Users\%USERNAME%\AppData\Roaming\AFFiNE-internal"`

It is due to some regression issue in 0.7.0-canary.52 and fixed in canary.56.

**Comment by Mojicode** [comment]
> Sorry but I guess you need to cleanup these workspaces. The fastest way to delete all of these is to remove the cache folder, which will remove ALL data for the canary version. Before doing this, please export the workspace through setting before doing so.
> 
> * Open cmd (search for cmd in the Start menu).
> * Copy the following and press Enter:
>   `rd /s /q "C:\Users\%USERNAME%\AppData\Roaming\AFFiNE-internal"`
> 
> It is due to some regression issue in 0.7.0-canary.52 and fixed in canary.56.

I have no fold like "AFFiNE-internal" in "C:\Users\%USERNAME%\AppData\Roaming, there is just a AFFiNE-Canary

**Comment by pengx17** [comment]
Ops, sorry, please remove AFFiNE-Canary folder instead.

**Comment by Mojicode** [comment]
> Ops, sorry, please remove AFFiNE-Canary folder instead.

I uninstall canary and re-install new canary version, it has gone.
