### ISSUE TITLE
support disable plugin

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3515]

**Comment by Wzb3422** [comment]
Hi Alex 👋, 
I am interested in the AFFiNE project and would like to address this specific issue at hand.
Having delved into the project and carefully reviewed the code related to the build workflow and plugin registration, I have got a grasp of the relevant areas. I know where to intervene and disable the plugin as required. However, in order to proceed with precision and align with the project's objectives, I believe it is imperative to acquire further context and details regarding the preferred approach to plugin disablization.
I kindly request your guidance in this matter. It would be immensely valuable if we could engage in a detailed discussion to clarify the desired outcome, expectations, and any specific considerations. Your insights and direction will undoubtedly assist me in contributing meaningfully to the project. This could lead me further in making future contributions to this project as well.
Thank you for considering my request. I am eager to collaborate and contribute to the success of the AFFiNE project.

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/pull/3605

**Comment by himself65** [comment]
> 

Sorry for the late response.

The plugin infra is one of the very important parts of our AFFiNE ecosystem. So It's mainly written only by core members (for now only myself). I need to write the whole frame first then I think I can separate some detail jobs to the community.

I think there do have some extra enhancements in the current plugin system. Let me list it here a little

- cache plugin code into `indexeddb`
- plugin permission control (fetch API)
- ShadowRoot for each dom
- Virtual environment for every single plugin like https://github.com/salesforce/near-membrane

But the main goal is to build a safety sandbox into our AFFiNE.

Plugin infra is a tough part that needs much architecture experience and engineering design. Good to know some discussion and feedback on this part
