### ISSUE TITLE
[feature]: docker support raspberry pi 

### ISSUE THREAD

**Issue by May-Yaha** [toeverything/AFFiNE#377]
### 1~3 main use cases of the proposed feature

dockerfile support armv8?

**Comment by darkskygit** [comment]
hi, our docker image support armv8: https://github.com/toeverything/AFFiNE/pkgs/container/affine

**Comment by May-Yaha** [comment]
> hi, our docker image support armv8: https://github.com/toeverything/AFFiNE/pkgs/container/affine

thx

**Comment by May-Yaha** [comment]
no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by TheNexter** [comment]
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by darkskygit** [comment]
**[nightly-server-latest](https://github.com/orgs/toeverything/packages/container/affine/45255230?tag=nightly-server-latest)** tag now supoort amd64/armv8/armv7, both amd64 and armv8 have been tested by hardware(9900t for amd64, rk3389/m2 for armv8), but since i don't have an armv7 device on hand, so i only tested it with qemu. if you having problems when using the armv7 version, please submit a new issue
