### ISSUE TITLE
The restart update of the client will lag for a while.

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#3834]
The desired effect is that after clicking restart to update, the client disappears immediately, providing timely feedback to the user. Otherwise, some other product strategies will be needed to handle this.
Updating the client is a process that every user will encounter, and we need to attach importance to the user experience of this process.

**Comment by pengx17** [comment]
The issue might be caused by how electron-updater works on **Mac**.
After downloaded, on requesting update by calling `quitAndInstall` (https://github.com/electron-userland/electron-builder/blob/dcb63100fff961bf1ee2c99ded465a061d4202ef/packages/electron-updater/src/MacUpdater.ts#L215), it will:
- start a local server that serves the downloaded app
- invoking native updater's `checkForUpdates`
	- Yes, `electron-updater` package relies on the Electron buildin's updater to handle install
	- when native updater requesting for update, it will requesting the local server for the new app, instead of requesting from remote provider
- after native updater finished downloading, it will quit the app and then replace the existing app with the new one automatically

If the app size is large (in our case, the file size + number of files is both quite large), the update process could take a while. I think reduce the number of bundled files AND using ASAR may increase the speed of update on quit.

The above case may not be the same for Windows, but I guess reducing the number of bundled files will also improve the speed of installing from .exe as well.
