### ISSUE TITLE
inconstant guid in server side

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#4132]
There are different formats in the database 

- `${workspaceId}` (uuid)
- `${workspaceId}:space:${pageId}` (uuid:space:nanoid)
- `space:${pageId}` (space:nanoid)

The reason is server will use `uuidv4` as the id generator, but in the frontend will use `nanoid` with `${workspaceId}:space:` as the prefix.

This might cause the SQL table's primary key inconsistent, and hard to lookup the document because there are three types of id for some reason.

What's more, there already some issues in the existing codespace.

Example:
https://github.com/toeverything/AFFiNE/blob/4f97ea8a5d7cda629e6d17345d74a017b18bfcf5/apps/server/src/modules/workspaces/permission.ts#L52-L55

We need to cralify the guid with same format in both frontend and backend

**Comment by himself65** [comment]
In the future, we will have the doc whose GUID is `${workspaceId}:setting:${userId}` (uuid:setting:randomNumber)

**Comment by forehalo** [comment]
`${workspaceId}:${variant}:${sub_id}` or `workspaceId + ${variant}:${sub_id}` are both cool for backend.

> To be clear, the server will only generate uuid v4 for workspace id not for subdocs, they are all done in the frontend.

What's really important is once we choose one, we should keep the format forever. The issues we currently face are caused by the inconsistent format for guid passed to server. We've seen 3 kinds of subdoc guid in our codebase. We can't always keep the server updated with such changes, especially when the frontend/server are separated maintained and it's goanna be very hard to maintain the backward compatibility as well.

```
1. spaces:${nanoid}
2. ${workspaceId}:spaces:${nanoid}
3. ${no-workspaceId}:spaces:${nanoid}
  ^^^^^^^^^^^^^^ workspace id generated in frontend
```

The easiest way to solve this is making a custom type to represent the subdoc id(not guid):
```ts
// An interesting thing is the custom type for subdoc id can be furtherly used
// to restrict the websocket gateway and frontend API calling types 
type SubDocId = {
  workspace: String // workspace id
  variant: Enum     // spaces or settings or what's new in the future
  id: String        // guid part under workspace
}
```

One rare case I don't have time to investigate yet is somehow the subdoc id was given `${frontend-workspaceId}:spaces:${nanoid}`,
 but the correct server-generated `workspaceId` is given at the same time when syncing. there must be a potential bug in the frontend syncing logic.
