### ISSUE TITLE
After exporting to png, the display quality is poor​

### ISSUE THREAD

**Issue by greedyhao** [toeverything/AFFiNE#4427]
### What happened?

As shown in the figure
![QQ截图20230920135201](https://github.com/toeverything/AFFiNE/assets/25771942/ebbd0639-4270-477b-99ba-9e49f9c351a6)

Version: 0.8.3

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
@fourdim please take a look.

**Comment by fourdim** [comment]
For the copy as png option. It not only depends on the AFFiNE application but also depends on the platform you are pasting to.
AFFiNE does reduce a little bit quality to ensure the application won't get stuck. 
However, quality of this poor does not seem to be AFFiNE's fault.

Many platforms choose to compress images in order to cut costs.
Unfortunately, the platform you are pasting to might be one of them.

You can try to use your system's built in screenshot and paste it to the target platform. Then, see if the quality reduced to prove this.

MacOS: `Command`+`shift`+`3`
Windows: `Win` + `shift` + `s`

In my case:

In terms of slack,
<img width="1262" alt="image" src="https://github.com/toeverything/AFFiNE/assets/59462000/6b59ab7a-70d9-42f6-9632-9f79fc3d5965">
Original:
![image](https://github.com/toeverything/AFFiNE/assets/59462000/dcad20e2-15cf-406c-a24d-01a7034b140b)

BTW, I strongly recommend you to use system's builtin screenshot. It can be thousands times faster and the quality can be many times better.

I would like to close this issue. If you find that it's AFFiNE's fault, feel free to reopen it.

**Comment by greedyhao** [comment]
@fourdim If the entire page is exported to pdf or png, the display quality is still relatively poor

**Comment by fourdim** [comment]
That is expected. It's the limitation of js and browsers. Unfortunately, there is nothing we can do (at least for now).

Edgeless is using `html2canvas` which is a js library whereas note is using browser's native api. The compression of edgeless one is done by https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL, it is just not adjustable as it's also a native web api.

I still recommend you zoom in and then take a screenshot.

**Comment by greedyhao** [comment]
But on pages like draw.io excalidraw, the quality of exported images is guaranteed. Can we use their technology?

**Comment by fourdim** [comment]
https://github.com/jgraph/drawio/blob/45f88bc27ebe62f65a09a48d4b1a8d914df3ba97/src/main/webapp/js/diagramly/vsdx/mxVsdxCanvas2D.js#L494
We are providing the same quality in terms of exporting to png.

**Comment by greedyhao** [comment]
I see
May be we can add an option of export as svg file
