### ISSUE TITLE
Selecting & Navigation Issues with Databases​

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4619]
### What happened?

https://jumpshare.com/v/4n0rkbZZdLfWQIXJsL1L

here is a gif. sometimes selecting cause to move, sometimes it selects the wrong cell (I think it happens if the table is in a space narrower than its container)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
1. Just to confirm, were you operating the database in Edgeless Mode?
2. Could you please describe the specific actions you took? It’s still not clear from the GIF.

**Comment by kemalakcc** [comment]
Sorry, I've tried a more clear one here: https://jumpshare.com/v/A7LeSLIAjZpRx11AbJvb

The issue is, as you can see from this one, I'm trying to select more than one line from the table but this also causes me to move on the edgeless board in a weird way (I select rows from above and my board moves below, etc)

In the previous gif, you can also see some weird behavior. for example, I'm selecting a cell that highlights the cell on the left (not the selected one). This type of issue becomes less probable when I increase the width of the container. But navigation problems are still a thing.

Hope it helps!
