### ISSUE TITLE
Sort by, in table and kanban view​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4621]
### Description

So drag & drop is not always the solution. It would be great to have a Sort By , or Order By like the filter so we can change the order based on some column

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. Currently, this is in the future iteration plan, but it has not started yet. You can track the progress here https://github.com/toeverything/blocksuite/issues/4395

**Comment by kevin61416** [comment]
This issue seems premature to close, as only the group-by feature is complete, while the **sort-by feature is still pending.**

As a forward-thinking knowledge management/note-taking app, lacking table sorting support is quite surprising.

Additionally, I suggest adding **tag-number mapping** functionality to the sort-by feature, which would greatly enhance the user experience. For example, urgent-4, high-3, medium-2, low-1. This way, the kanban can display the tag key and sort by the number value (instead of alphabetical sorting).

Overall, this is a fantastic and promising app! 😆
