### ISSUE TITLE
z-index bug:  when open a deleted page, button's tooltip was wrong

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#4716]
### What happened?

![shot-2023-10-25-10 48 50@2x](https://github.com/toeverything/AFFiNE/assets/24713927/4c1ef398-e283-4c45-9902-55204e220c5a)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
cc @JimmFly

**Comment by sandy088** [comment]
Hey @hwangdev97 I want to work on this, can you please assign it to me?

**Comment by pengx17** [comment]
Should be fixed by https://github.com/toeverything/AFFiNE/pull/5169 already

**Comment by sandy088** [comment]
> Should be fixed by #5169 already

Hey @pengx17  @hwangdev97 ,

Ok, that's good, but @pengx17 kindly please can you tell me how this issue is being resolved, because I've been trying to fix the issue with the tooltip and z-index on the trash page. I've experimented with z-index on , tooltip, trash-page-button-groups, and help-island (possibly everywhere from where the Delete button's tooltip can affected), but it doesn't seem to be the problem, Z-index property is not working on all these places. It could be related to how the elements are placed, possibly due to nested stacking contexts.

I have a potential solution in mind: moving the tooltip to the left side of both the delete and restore buttons, as shown in the image. What do you think? Should I go ahead and make a pull request for this?

![Screenshot 2023-12-06 203947](https://github.com/toeverything/AFFiNE/assets/90024312/46e7a4c4-7e48-48ce-bc12-0bdbd2d165f8)
![Screenshot 2023-12-06 204002](https://github.com/toeverything/AFFiNE/assets/90024312/84420db8-e1e3-4c3a-9c49-16104e0ead45)


Let me know your thoughts...

**Comment by sandy088** [comment]
> Should be fixed by #5169 already

Hey @pengx17  @hwangdev97

Still this issue is not fixed in #5169 can so, can I make a pull request with the above fixes that I have done?
