### ISSUE TITLE
Double-click window's title bar to zoom

### ISSUE THREAD

**Issue by fundon** [toeverything/AFFiNE#4995]
### What happened?

1. First double-click, the window should be zoomed
2. Second double-click, resize back

<img width="489" alt="Screenshot 2023-11-20 at 07 35 53" src="https://github.com/toeverything/AFFiNE/assets/27926/9ee07398-43ca-4ec2-9531-ae9004253a82">

https://github.com/toeverything/AFFiNE/assets/27926/89b484c9-2b82-4d19-9adc-ec1e5dee517b

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Hi Tsai,

The logic currently is exactly what you said.
- First double-click, the window be zoomed
- Second double-click, resize back

I'm not sure what the problem is.

But I found that the area where you can double-click to control zoom seems a bit small, there is only a thin bar at the top of the window, maybe we can make it larger.

**Comment by fundon** [comment]
I checked my system services. Stoped the yabai service. It works good.

By the way, when yabai is enabled, only a few apps can't reach it, includes AFFiNE.
