### ISSUE TITLE
​Cannot copy and paste

### ISSUE THREAD

**Issue by huangtc** [toeverything/AFFiNE#5610]
### What happened?

​Cannot copy and paste

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
please give more information

**Comment by ilaipi** [comment]
maybe it's because the EOL character. 

I am on windows 11, when I generate sql with Datagrip to query console, and then copy the sql to the code block of affine,
got all empty lines.

If I paste the sql to console of chrome, and then re-copy from the console, and then paste to affine, got all lines.

**Comment by fourdim** [comment]
Fixed in the latest release.

**Comment by aruiplex** [comment]
> Fixed in the latest release.

Hi! I am a self-host user, I pulled the docker image(ghcr.io/toeverything/affine-graphql:stable) today, and I found I cannot copy the text from the affine web page (Chrome in macOS). You can recheck it maybe.

**Comment by fourdim** [comment]
> > Fixed in the latest release.
> 
> Hi! I am a self-host user, I pulled the docker image(ghcr.io/toeverything/affine-graphql:stable) today, and I found I cannot copy the text from the affine web page (Chrome in macOS). You can recheck it maybe.

Hi, could you please describe what exactly happens when you are copying and pasting?
Does the tab response? Is there any error messages in the browser's console?
If you are stuck when you are copying and pasting content that contains images or files, we recently fixed it in https://github.com/toeverything/blocksuite/pull/7094.

**Comment by aruiplex** [comment]
Hi! Here are the details about this bug:

1. I could copy text/image/URL/etc from other places and paste it to the affine webpage in the browser.
2. I cannot copy anything in the affine browser. When I press `cmd+c` to copy something in the affine webpage, nothing happens. The clipboard is the last thing I copied from other places. The web console will display an error.

```
TypeError: Cannot read properties of undefined (reading 'write')
    at l.writeToClipboard (index.ts:214:31)
    at async l.copySlice (index.ts:244:5)
```

Thx.

Some other errors I also show here may help:

<img width="763" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40193711/3fc95e9a-7076-4103-ac93-823e0487e3a9">

**Comment by fourdim** [comment]
> Hi! Here are the details about this bug:
> 
> 1. I could copy text/image/URL/etc from other places and paste it to the affine webpage in the browser.
> 2. I cannot copy anything in the affine browser. When I press `cmd+c` to copy something in the affine webpage, nothing happens. The clipboard is the last thing I copied from other places. The web console will display an error.
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'write')
>     at l.writeToClipboard (index.ts:214:31)
>     at async l.copySlice (index.ts:244:5)
> ```


Unfortunately, due to the restriction of browsers, many features like [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) only work under [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (i.e. HTTPS or localhost). I would recommend you either setup your own CA, or proxy the server to the localhost.

**Comment by aruiplex** [comment]
Hi, you can set the flag in Chrome to disable the Secure Contexts in the trusted sources. Input the `chrome://flags/#unsafely-treat-insecure-origin-as-secure` in URL to set.
