### ISSUE TITLE
Workspace Performance Issue Due to Continuous Cloud Sync

### ISSUE THREAD

**Issue by mkosif** [toeverything/AFFiNE#6405]
### What happened?

After enabling cloud sync for our workspace, it started working very slowly because it tried to sync with every keystroke. Additionally, there seems to be no option to disable 'cloud sync' once it has been enabled.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
We are currently working on optimizing the performance of cloud workspaces, and the inability to shut down cloud services is also a known issue.

**Comment by EYHN** [comment]
Sorry for the bad experience.

Is there any specific manifestation of the "very slowly" you mean? and how many documents are there in your workspace?

**Comment by schromp** [comment]
I have the same issue. I have about 4 small pages in the cloud workspace (not selfhosted) and i get a delay of roughly 0.5 to 1 second until it recognizes my keystroak.

This is on a 2,6 GHz 6-Core Intel Core i7 Mac from 2019 and over a wifi connection.

The same workspace on a pc connected over ethernet does not have this problem.
I would love to see a solution that makes typing as seemless over a less stable network because this delay makes efficient note taking almost impossible. :cry:

**Comment by mkosif** [comment]
> Sorry for the bad experience.
> 
> Is there any specific manifestation of the "very slowly" you mean? and how many documents are there in your workspace?

For the test using only 1 doc in my workspace.  As @schromp mentioned, it causes lags during typing because of syncing each keystroke.

**Comment by mkosif** [comment]
It's fixed after update to version 0.13.4 (editor version: 0.14.0-canary-202403250855-4171ecd).
