### ISSUE TITLE
​Improve the smoothness of opening pages

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#6414]
### Description

Improve the smoothness and responsiveness of opening pages to make them smoother, currently there is some lag that is noticeable. When I try to open a page there is a random lag of 1-3 seconds. Especially when opening a page with a table, even if there are not many characters within the page, it will lag. I use web and Windows client versions.

Thank you for your hard work and I hope you will continue to focus on the smoothness of the application in subsequent releases.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Thank you for reporting the issue. We have found a performance issue with the current table block and have a fix, will be included in the next version.

We will continue to make some improvements for other performance issues. If you encounter any specific problems that feel slow, you can reply directly!

Since this issue is not associated with any specific work, I will close it and we can continue the discussion.
