### ISSUE TITLE
Option to remove / Reduce distracting Animation​s

### ISSUE THREAD

**Issue by MarArMar** [toeverything/AFFiNE#6430]
### Description

Just started using Affine

Tried database

I used Notion & want to use Affine for focus and work.

I do not want distracting animations playing all the time

Every time I click on a column name, it plays a complex & distracting animation, how to remove this ?

![Affine distracting things](https://github.com/toeverything/AFFiNE/assets/136232300/fe0e9624-4cc5-4c88-be83-d4666044717e)

### Use case

Focus

**Comment by EYHN** [comment]
I think this is by design? @hwangdev97 
Maybe we can provide a no-animation mode...

**Comment by hwangdev97** [comment]
Yes, it's by design. This animation means you can drag the column and move it either to the right or left.  

The reason for having this animation is that there are both click and hover actions on the title of the column. We need a metaphor to tell everyone that holding down here can drag it.

At present, this animation only appears in this place. We need to reuse it in other places so that more people know how to start dragging.

And I think so, we can provide a no-animation mode in the future.

**Comment by MarArMar** [comment]
"The reason for having this animation is that there are both click and hover actions on the title of the column. We need a metaphor to tell everyone that holding down here can drag it."

Users don't need to be reminded every single time that this is a possibility, maybe the first time only ?

If there is an option to disable it it would be super welcome in my opinion

**Comment by forehalo** [comment]
related to #5864
