### ISSUE TITLE
"manifest unknown" when trying to pull AFFiNE locally first (nightly-latest) [bug]: 

### ISSUE THREAD

**Issue by cejuo** [toeverything/AFFiNE#671]
### Describe the bug

Can't pull docker, it says "manifest unknown"

### To Reproduce

Steps to reproduce the behavior
1. run `docker pull ghcr.io/toeverything/affine:nightly-latest` as described in [docs](https://docs.affine.pro/affine/getting-started/install-affine-with-docker) to run AFFINE locally first.
2. See error on terminal:
```
nightly-latest: Pulling from toeverything/affine
manifest unknown
```

### Expected behavior

Pull docker correctly

### Platform

MacOS Apple Silicon

**Comment by darkskygit** [comment]
Hello, due to some ci errors, the image has been damaged, and we have repaired it. At present, the new image is stored in: https://github.com/toeverything/AFFiNE/pkgs/container/affine-self-hosted

You can use this command to download our latest image for use:
`docker pull ghcr.io/toeverything/affine-self-hosted:latest`

In addition, we have retained our old version of the image. 

If you want to continue to use the old version (pre-alpha aka livedemo), you can download it using the following command:
`docker pull ghcr.io/toeverything/affine-self-hosted:pre-alpha`

We will update the relevant documents and blog posts next week.
