### ISSUE TITLE
Block reference in same page or other page。​

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#6862]
### Description

I can't find a way to reference a block from the same page or other page. It can only link whole other page.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
same with #5907

**Comment by Mojicode** [comment]
> same with #5907
Hi, @EYHN 
It's not the same thing，I means that block in a page can be referenced in the same page or other page.
There are two example below:
<img width="612" alt="image" src="https://github.com/toeverything/AFFiNE/assets/30165217/381200f2-e4d2-4ba8-8a61-b65846f25791">

<img width="658" alt="image" src="https://github.com/toeverything/AFFiNE/assets/30165217/505bedb8-10dc-4e9c-979a-fa06eba19302">

**Comment by houshasen** [comment]
I would like to have this feature as well. Essentially, it functions like HTML linking within a page, i.e., an element link. This would be particularly helpful in long-form writing because there are times when each target block is specific to the current document's scope. Creating atomic notes just to jump between sections does not make sense in these cases.
