### ISSUE TITLE
Linux Desktop Client Unexpectedly Closes When Switching to Full Screen Mode

### ISSUE THREAD

**Issue by andreeado** [toeverything/AFFiNE#6978]
### What happened?

I am experiencing a consistent issue with the desktop client application on Linux. Whenever I attempt to switch the application to full screen mode—either by clicking the full screen button or by dragging the window to expand it—the application immediately closes. This occurs every time the action is attempted, resulting in the inability to use the application in full screen mode.

### Distribution version

Linux

### Are you self-hosting?

- [ ] Yes

### Anything else?

Operating System: 
NAME="Linux Mint"
VERSION="21.3 (Virginia)"

**Comment by jackyq2015** [comment]
I use Ubuntu 24.04 and had the similar issue. But it happens when startup.
```
    '      getBaseDownloadPath(tag, fileName) {\n' +
    '        return `${this.basePath}/download/${tag}/${fileName}`;\n' +
    '      }\n' +
    '    }'
}
08:57:29.219 (main) › [helper] forked 13722
08:57:29.495 (main) › create window
08:57:29.641 (main) › loading page at file://.
08:57:29.720 (main) › [ipc-event] ui:onMaximized [ true ]
Segmentation fault
```

Then i upgraded to [0.15.0-canary.10](https://github.com/toeverything/AFFiNE/releases/tag/v0.15.0-canary.10). Seems I can startup if use this version. But to my surprise, all the notes are gone! Not sure if my db file was wiped out or it was not migrated. where should I locate the db file and how can  I update it? Thanks

**Comment by forehalo** [comment]
duplicated [6879](https://github.com/toeverything/AFFiNE/issues/6978)
