### ISSUE TITLE
S3 Storage Service

### ISSUE THREAD

**Issue by LYUYork** [toeverything/AFFiNE#7384]
### Description

alternative to AWS s3, such as Minio?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
not planned

**Comment by medzhidov** [comment]
> not planned

Why not? It is easy, all you need is only [endpoint](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html) parameter and [forcePathStyle](https://sdk.amazonaws.com/swift/api/awss3/0.35.0/documentation/awss3/endpointparams/forcepathstyle) for full support

**Comment by dr3st** [comment]
@medzhidov 
Great info for you, I got Minio + Affine running, maybe this is helping you.
Go to admin portal:

Enable aws-s3 
Bucket: <select name of your choice>
config:

`
{"region":"auto","endpoint":"https://local.minio.behind.proxy.com","credentials":{"accessKeyId":"affine","secretAccessKey":"xxxxxxxxxxxxxxx"},"forcePathStyle":true}
`

I think this works, because the whole config is passed to the S3Client, which you can use to config it as you like to :)
I tested wrong configuration as well (wrong password), which results in

`
Failed to put object ({"key":"xxxxx/xxxxxxxxx","bucket":"affine","metadata":{"contentLength":224158,"checksumCRC32":"xxxxx","contentType":"image/jpeg"}})
[Nest] 1  - 07/03/2025, 5:35:45 PM   ERROR [GraphQL] <selfhosted:http:xxxxxxxx> internal_server_error
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
`

**Comment by jm809** [comment]
Add a release notes that this the final [[ ending-support-major ]] -x-y release
