### ISSUE TITLE
​Disable Demo Workspace - selfhosted

### ISSUE THREAD

**Issue by AtmOz-Design** [toeverything/AFFiNE#9178]
### Description

Hello Affine team, and thank you for your really great work. Affine is awesome.

The only feature that miss for my use is that it could be really nice to disable demo workspace on self-hosted version.

for now I have locked the application on my server via authentik but it is not optimal I find. I think a connection interface would be the best way without access to a demo workspace after admin already configure affine.

Maybe there is already an approach to disable the demo workspace?

Thank you in advance!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
Thanks for the suggestion, but we're not planning to address this request at the moment. The reason is that we currently don't have the resources to differentiate between self-hosted and mainline `app.affine.pro` . We aim to keep the codebase the same for both self-hosted and  `app.affine.pro`.

Our demo workspace is a crucial way for users (who from SEO or other way) to quickly experience our product, so we won't be modifying this logic for now.
